resources:
- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse-bosh-target}}
    username: {{concourse-bosh-username}}
    password: {{concourse-bosh-password}}
    deployment: {{concourse-bosh-deployment}}

- name: continuous-integration
  type: git
  source:
    uri: {{continuous-integration-remote}}
    private_key: {{gpdb-git-key}}
    branch: {{continuous-integration-branch}}

- name: concourse-release
  type: github-release
  source:
    repository: concourse
    user: concourse

- name: concourse-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-io-stemcell}}

jobs:
- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: concourse-release
      trigger: false
      params:
        globs:
        - concourse-*.tgz
        - garden-runc-*.tgz
    - get: continuous-integration
      trigger: false
    - get: concourse-stemcell
      trigger: false
  - put: concourse-deployment
    params:
      manifest: {{concourse-config-manifest-location}}
      releases:
        - concourse-release/concourse-*.tgz
        - concourse-release/garden-runc-*.tgz
      stemcells:
        - concourse-stemcell/*.tgz
