## ======================================================================
## resources
## ======================================================================

resources:
- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    private_key: {{gpdb-git-key}}
    uri: {{gpdb-git-remote}}

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
    username: {{docker_username}}
    password: {{docker_password}}

- name: bin_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: sync_tools_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: sync_tools_gpdb/sync_tools_gpdb.tar.gz

## ======================================================================
## jobs
## ======================================================================

# Stage 1: Build and C Unit Tests

jobs:

- name: compile_gpdb_centos6
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: centos-gpdb-dev-6
  - task: compile_gpdb
    file: gpdb_src/concourse/tasks/compile_gpdb.yml
    image: centos-gpdb-dev-6
    params:
      IVYREPO_HOST: {{ivyrepo_host}}
      IVYREPO_REALM: {{ivyrepo_realm}}
      IVYREPO_USER: {{ivyrepo_user}}
      IVYREPO_PASSWD: {{ivyrepo_passwd}}
      TARGET_OS: centos
      TARGET_OS_VERSION: 6
      BLD_TARGETS: ""
  - aggregate:
    - put: bin_gpdb_centos
      params:
        file: gpdb_artifacts/bin_gpdb.tar.gz
    - put: sync_tools_gpdb_centos
      params:
        file: sync_tools_gpdb/sync_tools_gpdb.tar.gz

# Stage 2: CS Tests
- name: cs-uao
  plan:
  - aggregate:
    - get: gpdb_src
      params: {submodules: none}
      passed: [compile_gpdb_centos6]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos6]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos6]
      trigger: true
    - get: centos-gpdb-dev-6
  - task: uao_orca_both_regression
    file: gpdb_src/concourse/tasks/tinc_gpdb.yml
    image: centos-gpdb-dev-6
    params:
      MAKE_TEST_COMMAND: uao_orca_both_regression
      TEST_OS: centos

- name: cs-subtransaction
  plan:
  - aggregate:
    - get: gpdb_src
      params: {submodules: none}
      passed: [compile_gpdb_centos6]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos6]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos6]
      trigger: true
    - get: centos-gpdb-dev-6
  - task: sub_transaction_limit_removal
    file: gpdb_src/concourse/tasks/tinc_gpdb.yml
    image: centos-gpdb-dev-6
    params:
      MAKE_TEST_COMMAND: sub_transaction_limit_removal
      TEST_OS: centos

- name: cs-fts
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      params: {submodules: none}
      passed: [compile_gpdb_centos6]
    - get: sync_tools_gpdb
      resource: sync_tools_gpdb_centos
      passed: [compile_gpdb_centos6]
    - get: bin_gpdb
      resource: bin_gpdb_centos
      passed: [compile_gpdb_centos6]
      trigger: true
    - get: centos-gpdb-dev-6
  - aggregate:
    - task: fts_transitions_part01
      file: gpdb_src/concourse/tasks/tinc_gpdb.yml
      image: centos-gpdb-dev-6
      params:
        MAKE_TEST_COMMAND: fts_transitions_part01
        TEST_OS: centos
    - task: fts_transitions_part02
      file: gpdb_src/concourse/tasks/tinc_gpdb.yml
      image: centos-gpdb-dev-6
      params:
        MAKE_TEST_COMMAND: fts_transitions_part02
        TEST_OS: centos
    - task: fts_transitions_part03
      file: gpdb_src/concourse/tasks/tinc_gpdb.yml
      image: centos-gpdb-dev-6
      params:
        MAKE_TEST_COMMAND: fts_transitions_part03
        TEST_OS: centos
