book_repo: greenplum-db/gpdb-docs/book

public_host: localhost:9292

dita_sections:
- repository:
    name: dita
  directory: docs-gpdb
  ditamap_location: gpdb-webhelp.ditamap

template_variables:
  book_title: Greenplum Database Documentation
  book_title_short:  Greenplum Database Docs
  domain_name: greenplum.org
  product_link: <div class="header-item"><a href="http://greenplum.org">Back to Greenplum Database</a></div>
  product_url: http://greenplum.org
  support_call_to_action: <a href="http://greenplum.org#contribute" target="_blank">Need Support?</a>
  support_link: <a href="https://github.com/greenplum-db/greenplum-db.github.io/wiki">Wiki</a>
  support_url: http://greenplum.org

broken_link_exclusions: iefix|arrowhead
