platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    username:
    password:
inputs:
  - name: gpdb_src
  - name: bin_gpdb
run:
  path: gpdb_src/concourse/scripts/regression_tests_gphdfs.bash
