platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-coverity
inputs:
  - name: gpdb_src
outputs:
  - name: gpdb_coverity_artifacts
run:
  path: gpdb_src/concourse/scripts/scan_with_coverity.bash
params:
  OUTPUT_ARTIFACT_DIR: gpdb_coverity_artifacts
  IVYREPO_HOST:
  IVYREPO_PASSWD:
  IVYREPO_REALM:
  IVYREPO_USER:
  COVERITY_TOKEN:
  COVERITY_EMAIL:
