platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
  - name: rc_bin_gpdb
run:
  path: gpdb_src/concourse/scripts/separate_qautils_files_for_rc.bash
params:
  QAUTILS_FILES: gpdb_src/gpAux/releng/NON_PRODUCTION_FILES.txt
  INPUT_TARBALL: bin_gpdb/bin_gpdb.tar.gz
  OUTPUT_TARBALL: rc_bin_gpdb/bin_gpdb.tar.gz
  QAUTILS_TARBALL: rc_bin_gpdb/QAUtils-OS-x86_64.tar.gz
