platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
    username:
    password:
inputs:
  - name: gpdb_src
  - name: bin_gpdb
params:
  EC2_PRIVATE_KEY:
  EC2_INSTANCE_IP:
run:
  path: gpdb_src/concourse/scripts/staging_server_gpcloud.bash
