platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
    username:
    password:
inputs:
  - name: gpdb_src
run:
  path: gpdb_src/concourse/scripts/unit_tests_gpcloud.bash
